name: spotlight_bottom_navbar
description: A customizable bottom navigation bar with spotlight effect for Flutter apps.
version: 0.0.6
homepage: https://github.com/Saravanan260203/spotlight_bottom_navbar
repository: https://github.com/Saravanan260203/spotlight_bottom_navbar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Add assets, fonts, or other package-specific configurations here.
